"""Comprehensive tests for the inventory template engine."""
import json
import pytest
import yaml

from app.services.inventory_templates import (
    InventoryTemplateEngine,
    Inventory,
    InventoryGroup,
    InventoryHost,
)


class TestInventoryTemplateEngine:
    @pytest.fixture
    def engine(self):
        return InventoryTemplateEngine()

    # Template registration
    def test_builtin_templates_registered(self, engine):
        templates = engine.available_templates
        assert len(templates) >= 5
        names = [t["name"] for t in templates]
        assert "growth" in names
        assert "enterprise_basic" in names
        assert "enterprise_ha" in names
        assert "air_gapped" in names
        assert "development" in names

    def test_growth_template_exists(self, engine):
        inv = engine.from_template("growth", {})
        assert "automationgateway" in inv.groups
        assert "automationcontroller" in inv.groups
        assert "automationhub" in inv.groups
        assert "automationeda" in inv.groups
        assert "database" in inv.groups

    def test_enterprise_basic_template_exists(self, engine):
        inv = engine.from_template("enterprise_basic", {})
        assert "automationgateway" in inv.groups
        assert len(inv.groups["automationgateway"].hosts) == 2
        assert "redis" in inv.groups

    def test_enterprise_ha_template_exists(self, engine):
        inv = engine.from_template("enterprise_ha", {})
        assert "execution_nodes" in inv.groups
        assert len(inv.groups["automationhub"].hosts) == 2
        assert "redis_mode" in inv.all_variables

    # INI rendering
    def test_render_ini_empty_inventory(self, engine):
        inv = Inventory()
        result = engine.render_ini(inv)
        assert "# AAP Inventory" in result
        assert "generated by InventoryTemplateEngine" in result

    def test_render_ini_single_group(self, engine):
        inv = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                )
            }
        )
        result = engine.render_ini(inv)
        assert "[web]" in result
        assert "web1.example.org" in result

    def test_render_ini_multiple_groups(self, engine):
        inv = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                ),
                "db": InventoryGroup(
                    name="db",
                    hosts=[InventoryHost(hostname="db1.example.org")],
                ),
            }
        )
        result = engine.render_ini(inv)
        assert "[web]" in result
        assert "[db]" in result
        assert "web1.example.org" in result
        assert "db1.example.org" in result

    def test_render_ini_group_vars(self, engine):
        inv = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                    variables={"ansible_user": "deploy", "port": 8080},
                )
            }
        )
        result = engine.render_ini(inv)
        assert "[web:vars]" in result
        assert "ansible_user=deploy" in result
        assert "port=8080" in result

    def test_render_ini_host_vars(self, engine):
        inv = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[
                        InventoryHost(
                            hostname="web1.example.org",
                            variables={"ansible_host": "192.168.1.10"},
                        )
                    ],
                )
            }
        )
        result = engine.render_ini(inv)
        assert "web1.example.org" in result
        assert "ansible_host=192.168.1.10" in result

    def test_render_ini_children(self, engine):
        inv = Inventory(
            groups={
                "prod": InventoryGroup(
                    name="prod",
                    hosts=[],
                    children=["web", "db"],
                ),
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                ),
                "db": InventoryGroup(
                    name="db",
                    hosts=[InventoryHost(hostname="db1.example.org")],
                ),
            }
        )
        result = engine.render_ini(inv)
        assert "[prod:children]" in result
        assert "web" in result
        assert "db" in result

    def test_render_ini_all_vars(self, engine):
        inv = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                )
            },
            all_variables={"ansible_python_interpreter": "/usr/bin/python3"},
        )
        result = engine.render_ini(inv)
        assert "[all:vars]" in result
        assert "ansible_python_interpreter=/usr/bin/python3" in result

    def test_render_ini_special_chars_escaped(self, engine):
        inv = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                    variables={"path": "/opt/app with spaces", "comment": "value#hash"},
                )
            }
        )
        result = engine.render_ini(inv)
        assert "[web:vars]" in result
        # Values with spaces or special chars should be quoted
        assert "path=" in result
        assert "'" in result or "spaces" in result

    # YAML rendering
    def test_render_yaml_empty_inventory(self, engine):
        inv = Inventory()
        result = engine.render_yaml(inv)
        assert "all:" in result
        assert "children:" in result

    def test_render_yaml_single_group(self, engine):
        inv = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                )
            }
        )
        result = engine.render_yaml(inv)
        assert "web:" in result
        assert "web1.example.org" in result

    def test_render_yaml_is_valid_yaml(self, engine):
        inv = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                )
            }
        )
        result = engine.render_yaml(inv)
        parsed = yaml.safe_load(result)
        assert "all" in parsed
        assert "children" in parsed["all"]
        assert "web" in parsed["all"]["children"]

    # JSON rendering
    def test_render_json_valid(self, engine):
        inv = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                )
            }
        )
        result = engine.render_json(inv)
        parsed = json.loads(result)
        assert "_meta" in parsed
        assert "web" in parsed
        assert "all" in parsed

    def test_render_json_contains_groups(self, engine):
        inv = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                )
            }
        )
        result = engine.render_json(inv)
        parsed = json.loads(result)
        assert parsed["web"]["hosts"] == ["web1.example.org"]

    # From config
    def test_from_config_growth(self, engine, default_config):
        inv = engine.from_config(default_config)
        assert "automationgateway" in inv.groups
        assert inv.groups["automationgateway"].hosts[0].hostname == "aap.example.org"
        assert "database" in inv.groups
        assert "redis" not in inv.groups
        assert inv.all_variables.get("ansible_connection") == "local"

    def test_from_config_enterprise(self, engine, enterprise_config):
        inv = engine.from_config(enterprise_config)
        assert len(inv.groups["automationgateway"].hosts) == 2
        assert "redis" in inv.groups
        assert "execution_nodes" in inv.groups
        assert inv.all_variables.get("redis_mode") == "cluster"

    def test_from_config_disconnected(self, engine, disconnected_config):
        inv = engine.from_config(disconnected_config)
        assert "bundle_install" in inv.all_variables
        assert inv.all_variables["bundle_install"] == "true"
        assert "bundle_dir" in inv.all_variables

    def test_from_config_has_all_groups(self, engine, default_config):
        inv = engine.from_config(default_config)
        required = {"automationgateway", "automationcontroller", "automationhub", "automationeda"}
        assert required.issubset(inv.groups.keys())

    def test_from_config_registry_vars(self, engine, default_config):
        inv = engine.from_config(default_config)
        assert "registry_username" in inv.all_variables
        assert "registry_password" in inv.all_variables

    # Validation
    def test_validate_valid_inventory(self, engine, default_config):
        inv = engine.from_config(default_config)
        errors = engine.validate_inventory(inv)
        assert errors == []

    def test_validate_empty_group_warning(self, engine):
        inv = Inventory(
            groups={
                "automationgateway": InventoryGroup(name="automationgateway", hosts=[]),
                "automationcontroller": InventoryGroup(
                    name="automationcontroller",
                    hosts=[InventoryHost(hostname="ctrl1.example.org")],
                ),
            }
        )
        errors = engine.validate_inventory(inv)
        assert any("automationgateway" in e and "no hosts" in e for e in errors)

    def test_validate_no_hosts_error(self, engine):
        inv = Inventory(
            groups={
                "automationgateway": InventoryGroup(name="automationgateway", hosts=[]),
                "automationcontroller": InventoryGroup(name="automationcontroller", hosts=[]),
            }
        )
        errors = engine.validate_inventory(inv)
        assert len(errors) >= 2
        assert any("no hosts" in e for e in errors)

    def test_validate_missing_required_groups(self, engine):
        inv = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                )
            }
        )
        errors = engine.validate_inventory(inv)
        assert any("automationgateway" in e or "automationcontroller" in e for e in errors)

    # Diff
    def test_diff_identical(self, engine, default_config):
        inv = engine.from_config(default_config)
        diffs = engine.diff_inventories(inv, inv)
        assert diffs == []

    def test_diff_host_added(self, engine):
        base = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                )
            }
        )
        new = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[
                        InventoryHost(hostname="web1.example.org"),
                        InventoryHost(hostname="web2.example.org"),
                    ],
                )
            }
        )
        diffs = engine.diff_inventories(base, new)
        host_added = [d for d in diffs if d["type"] == "host_added"]
        assert len(host_added) == 1
        assert host_added[0]["host"] == "web2.example.org"
        assert host_added[0]["group"] == "web"

    def test_diff_variable_changed(self, engine):
        base = Inventory(
            groups={"web": InventoryGroup(name="web", hosts=[InventoryHost("web1")])},
            all_variables={"foo": "bar"},
        )
        new = Inventory(
            groups={"web": InventoryGroup(name="web", hosts=[InventoryHost("web1")])},
            all_variables={"foo": "baz"},
        )
        diffs = engine.diff_inventories(base, new)
        var_changed = [d for d in diffs if d["type"] == "all_var_changed"]
        assert len(var_changed) == 1
        assert var_changed[0]["key"] == "foo"
        assert var_changed[0]["old"] == "bar"
        assert var_changed[0]["new"] == "baz"

    # Merge
    def test_merge_adds_groups(self, engine):
        base = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                )
            }
        )
        overlay = Inventory(
            groups={
                "db": InventoryGroup(
                    name="db",
                    hosts=[InventoryHost(hostname="db1.example.org")],
                )
            }
        )
        merged = engine.merge_inventories(base, overlay)
        assert "web" in merged.groups
        assert "db" in merged.groups
        assert merged.groups["db"].hosts[0].hostname == "db1.example.org"

    def test_merge_combines_hosts(self, engine):
        base = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web1.example.org")],
                )
            }
        )
        overlay = Inventory(
            groups={
                "web": InventoryGroup(
                    name="web",
                    hosts=[InventoryHost(hostname="web2.example.org")],
                )
            }
        )
        merged = engine.merge_inventories(base, overlay)
        hostnames = [h.hostname for h in merged.groups["web"].hosts]
        assert "web1.example.org" in hostnames
        assert "web2.example.org" in hostnames

    def test_merge_overlay_vars_win(self, engine):
        base = Inventory(
            groups={"web": InventoryGroup(name="web", hosts=[InventoryHost("web1")])},
            all_variables={"foo": "base_value"},
        )
        overlay = Inventory(
            groups={},
            all_variables={"foo": "overlay_value"},
        )
        merged = engine.merge_inventories(base, overlay)
        assert merged.all_variables["foo"] == "overlay_value"

    # Interpolation (via from_template)
    def test_interpolate_simple(self, engine):
        inv = engine.from_template("growth", {"gateway_host": "my-gateway.example.org"})
        gw_hosts = inv.groups["automationgateway"].hosts
        assert len(gw_hosts) == 1
        assert gw_hosts[0].hostname == "my-gateway.example.org"

    def test_interpolate_missing_var(self, engine):
        inv = engine.from_template("growth", {})
        # Uses default from template
        gw_hosts = inv.groups["automationgateway"].hosts
        assert gw_hosts[0].hostname == "aap.example.org"

    def test_interpolate_nested(self, engine):
        inv = engine.from_template("growth", {"ansible_connection": "ssh"})
        assert inv.all_variables.get("ansible_connection") == "ssh"

    def test_from_template_unknown_raises(self, engine):
        with pytest.raises(ValueError, match="Unknown template"):
            engine.from_template("nonexistent_template", {})
