import copy

import pytest

from app.models import DeploymentConfig
from app.inventory import InventoryGenerator


def _render(cfg_dict: dict) -> str:
    return InventoryGenerator(DeploymentConfig(**cfg_dict)).render()


def _validate(cfg_dict: dict) -> list[str]:
    return InventoryGenerator(DeploymentConfig(**cfg_dict)).validate()


# ---------------------------------------------------------------------------
# Growth topology
# ---------------------------------------------------------------------------


class TestInventoryGeneratorGrowth:
    """Tests for growth (all-in-one) topology inventory generation."""

    def test_generates_valid_ini_format(self, default_config):
        result = _render(default_config)
        assert result.startswith("#")
        assert "[all:vars]" in result
        assert "Generated by AAP Deployment Wizard" in result

    def test_contains_all_group_headers(self, default_config):
        result = _render(default_config)
        for group in [
            "automationgateway",
            "automationcontroller",
            "automationhub",
            "automationeda",
            "database",
            "all:vars",
        ]:
            assert f"[{group}]" in result

    def test_gateway_host_in_automationgateway(self, default_config):
        result = _render(default_config)
        lines = result.split("\n")
        idx = lines.index("[automationgateway]")
        assert lines[idx + 1] == "aap.example.org"

    def test_controller_host_in_automationcontroller(self, default_config):
        result = _render(default_config)
        lines = result.split("\n")
        idx = lines.index("[automationcontroller]")
        assert lines[idx + 1] == "aap.example.org"

    def test_hub_host_in_automationhub(self, default_config):
        result = _render(default_config)
        lines = result.split("\n")
        idx = lines.index("[automationhub]")
        assert lines[idx + 1] == "aap.example.org"

    def test_eda_host_in_automationeda(self, default_config):
        result = _render(default_config)
        lines = result.split("\n")
        idx = lines.index("[automationeda]")
        assert lines[idx + 1] == "aap.example.org"

    def test_single_host_in_all_groups(self, default_config):
        result = _render(default_config)
        for section in [
            "[automationgateway]",
            "[automationcontroller]",
            "[automationhub]",
            "[automationeda]",
        ]:
            lines = result.split("\n")
            idx = lines.index(section)
            assert lines[idx + 1] == "aap.example.org"

    def test_registry_credentials_in_all_vars(self, default_config):
        result = _render(default_config)
        assert "registry_username=testuser" in result
        assert "registry_password=testpass" in result

    def test_managed_database_vars(self, default_config):
        result = _render(default_config)
        assert "postgresql_admin_username=postgres" in result
        assert "postgresql_admin_password=dbpass123" in result

    def test_gateway_admin_password(self, default_config):
        result = _render(default_config)
        assert "gateway_admin_password=gwpass123" in result

    def test_controller_admin_password(self, default_config):
        result = _render(default_config)
        assert "controller_admin_password=ctrlpass123" in result

    def test_hub_admin_password(self, default_config):
        result = _render(default_config)
        assert "hub_admin_password=hubpass123" in result

    def test_eda_admin_password(self, default_config):
        result = _render(default_config)
        assert "eda_admin_password=edapass123" in result

    def test_network_ports(self, default_config):
        result = _render(default_config)
        assert "envoy_https_port" not in result
        assert "envoy_http_port" not in result

        cfg = copy.deepcopy(default_config)
        cfg["network"]["https_port"] = 8443
        cfg["network"]["http_port"] = 8080
        result = _render(cfg)
        assert "envoy_https_port=8443" in result
        assert "envoy_http_port=8080" in result

    def test_tls_settings_default(self, default_config):
        result = _render(default_config)
        assert "envoy_disable_https" not in result

    def test_tls_disabled(self, default_config):
        cfg = copy.deepcopy(default_config)
        cfg["network"]["tls"]["disable_https"] = True
        result = _render(cfg)
        assert "envoy_disable_https=true" in result

    def test_custom_tls_certs(self, default_config):
        """Inventory still renders correctly when custom TLS fields are set."""
        cfg = copy.deepcopy(default_config)
        cfg["network"]["tls"]["custom_ca_cert"] = "/etc/pki/ca.crt"
        cfg["network"]["tls"]["custom_server_cert"] = "/etc/pki/server.crt"
        cfg["network"]["tls"]["custom_server_key"] = "/etc/pki/server.key"
        result = _render(cfg)
        assert "[all:vars]" in result

    def test_install_dir(self, default_config):
        """Config carries install_dir; render succeeds."""
        model = DeploymentConfig(**default_config)
        assert model.install_dir == "/opt/aap"
        result = InventoryGenerator(model).render()
        assert len(result) > 0

    def test_redis_standalone(self, default_config):
        result = _render(default_config)
        assert "redis_mode=standalone" in result

    def test_seed_collections_false(self, default_config):
        result = _render(default_config)
        assert "hub_seed_collections=false" in result

    def test_seed_collections_true(self, default_config):
        cfg = copy.deepcopy(default_config)
        cfg["hub"]["seed_collections"] = True
        result = _render(cfg)
        assert "hub_seed_collections=true" in result

    def test_eda_safe_plugins(self, default_config):
        """EDA safe_plugins stored on the model; EDA section renders correctly."""
        model = DeploymentConfig(**default_config)
        assert "ansible.eda.webhook" in model.eda.safe_plugins
        result = InventoryGenerator(model).render()
        assert "eda_admin_password=edapass123" in result

    def test_controller_memory_capacity(self, default_config):
        result = _render(default_config)
        assert "controller_percent_memory_capacity" not in result

        cfg = copy.deepcopy(default_config)
        cfg["controller"]["percent_memory_capacity"] = 0.8
        result = _render(cfg)
        assert "controller_percent_memory_capacity=0.8" in result

    def test_per_component_db_passwords(self, default_config):
        result = _render(default_config)
        assert "gateway_pg_password=gwdbpass" in result
        assert "controller_pg_password=ctrldbpass" in result
        assert "hub_pg_password=hubdbpass" in result
        assert "eda_pg_password=edadbpass" in result

    def test_growth_has_local_connection(self, default_config):
        result = _render(default_config)
        assert "ansible_connection=local" in result

    def test_growth_has_database_section(self, default_config):
        result = _render(default_config)
        assert "[database]" in result

    def test_growth_no_redis_section(self, default_config):
        result = _render(default_config)
        assert "[redis]" not in result

    def test_growth_no_execution_nodes_section(self, default_config):
        result = _render(default_config)
        assert "[execution_nodes]" not in result

    def test_topology_comment(self, default_config):
        result = _render(default_config)
        assert "Growth (All-in-one)" in result


# ---------------------------------------------------------------------------
# Enterprise topology
# ---------------------------------------------------------------------------


class TestInventoryGeneratorEnterprise:
    """Tests for enterprise topology inventory generation."""

    def test_multiple_gateway_hosts(self, enterprise_config):
        result = _render(enterprise_config)
        lines = result.split("\n")
        idx = lines.index("[automationgateway]")
        assert lines[idx + 1] == "gw1.example.org"
        assert lines[idx + 2] == "gw2.example.org"

    def test_multiple_controller_hosts(self, enterprise_config):
        result = _render(enterprise_config)
        lines = result.split("\n")
        idx = lines.index("[automationcontroller]")
        assert lines[idx + 1] == "ctrl1.example.org"
        assert lines[idx + 2] == "ctrl2.example.org"

    def test_multiple_hub_hosts(self, enterprise_config):
        result = _render(enterprise_config)
        lines = result.split("\n")
        idx = lines.index("[automationhub]")
        assert lines[idx + 1] == "hub1.example.org"
        assert lines[idx + 2] == "hub2.example.org"

    def test_multiple_eda_hosts(self, enterprise_config):
        result = _render(enterprise_config)
        lines = result.split("\n")
        idx = lines.index("[automationeda]")
        assert lines[idx + 1] == "eda1.example.org"
        assert lines[idx + 2] == "eda2.example.org"

    def test_execution_nodes(self, enterprise_config):
        result = _render(enterprise_config)
        assert "[execution_nodes]" in result
        assert "exec1.example.org" in result

    def test_external_database_host(self, enterprise_config):
        result = _render(enterprise_config)
        assert "[database]" not in result

    def test_redis_cluster_mode(self, enterprise_config):
        result = _render(enterprise_config)
        assert "redis_mode=cluster" in result

    def test_enterprise_has_redis_section(self, enterprise_config):
        result = _render(enterprise_config)
        assert "[redis]" in result

    def test_enterprise_no_local_connection(self, enterprise_config):
        result = _render(enterprise_config)
        assert "ansible_connection=local" not in result

    def test_enterprise_per_component_db_names(self, enterprise_config):
        result = _render(enterprise_config)
        assert "gateway_pg_database=gateway" in result
        assert "controller_pg_database=controller" in result
        assert "hub_pg_database=hub" in result
        assert "eda_pg_database=eda" in result

    def test_enterprise_per_component_db_users(self, enterprise_config):
        result = _render(enterprise_config)
        assert "gateway_pg_username=gateway" in result
        assert "controller_pg_username=controller" in result
        assert "hub_pg_username=hub" in result
        assert "eda_pg_username=eda" in result

    def test_topology_comment(self, enterprise_config):
        result = _render(enterprise_config)
        assert "Enterprise" in result

    def test_hop_node_receptor_type(self, enterprise_config):
        cfg = copy.deepcopy(enterprise_config)
        cfg["execution_nodes"].append(
            {"host": "hop1.example.org", "receptor_type": "hop"}
        )
        result = _render(cfg)
        assert "hop1.example.org receptor_type='hop'" in result


# ---------------------------------------------------------------------------
# Disconnected installation
# ---------------------------------------------------------------------------


class TestInventoryGeneratorDisconnected:
    """Tests for disconnected (bundled) installation inventory."""

    def test_bundle_dir_in_vars(self, disconnected_config):
        result = _render(disconnected_config)
        assert "bundle_install=true" in result
        assert "bundle_dir=/opt/aap-bundle" in result

    def test_no_registry_credentials(self, disconnected_config):
        result = _render(disconnected_config)
        assert "registry_username" not in result
        assert "registry_password" not in result

    def test_disconnected_comment(self, disconnected_config):
        result = _render(disconnected_config)
        assert "Disconnected (Bundled)" in result


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


class TestInventoryValidation:
    """Tests for inventory configuration validation."""

    def test_valid_growth_config_no_errors(self, default_config):
        errors = _validate(default_config)
        assert errors == []

    def test_valid_enterprise_config_no_errors(self, enterprise_config):
        errors = _validate(enterprise_config)
        assert errors == []

    def test_empty_gateway_host_error(self, default_config):
        cfg = copy.deepcopy(default_config)
        cfg["gateway"]["hosts"] = []
        errors = _validate(cfg)
        assert any("gateway host" in e.lower() for e in errors)

    def test_empty_controller_host_error(self, default_config):
        cfg = copy.deepcopy(default_config)
        cfg["controller"]["hosts"] = []
        errors = _validate(cfg)
        assert any("controller host" in e.lower() for e in errors)

    def test_missing_admin_password_error(self, default_config):
        cfg = copy.deepcopy(default_config)
        cfg["gateway"]["admin_password"] = ""
        errors = _validate(cfg)
        assert any("gateway admin password" in e.lower() for e in errors)

    def test_missing_db_admin_password_error(self, default_config):
        cfg = copy.deepcopy(default_config)
        cfg["database"]["admin_password"] = ""
        errors = _validate(cfg)
        assert any("database admin password" in e.lower() for e in errors)

    def test_enterprise_needs_multiple_gateways(self, enterprise_config):
        cfg = copy.deepcopy(enterprise_config)
        cfg["gateway"]["hosts"] = ["gw1.example.org"]
        errors = _validate(cfg)
        assert any("2 gateway" in e.lower() for e in errors)

    def test_enterprise_needs_multiple_controllers(self, enterprise_config):
        cfg = copy.deepcopy(enterprise_config)
        cfg["controller"]["hosts"] = ["ctrl1.example.org"]
        errors = _validate(cfg)
        assert any("2 controller" in e.lower() for e in errors)

    def test_online_needs_registry_credentials(self, default_config):
        cfg = copy.deepcopy(default_config)
        cfg["registry"]["username"] = ""
        errors = _validate(cfg)
        assert any("registry username" in e.lower() for e in errors)

    def test_online_needs_registry_password(self, default_config):
        cfg = copy.deepcopy(default_config)
        cfg["registry"]["password"] = ""
        errors = _validate(cfg)
        assert any("registry password" in e.lower() for e in errors)

    def test_disconnected_skips_registry_check(self, disconnected_config):
        cfg = copy.deepcopy(disconnected_config)
        cfg["registry"]["username"] = ""
        cfg["registry"]["password"] = ""
        errors = _validate(cfg)
        assert not any("registry" in e.lower() for e in errors)

    def test_multiple_errors_returned(self, default_config):
        cfg = copy.deepcopy(default_config)
        cfg["gateway"]["admin_password"] = ""
        cfg["database"]["admin_password"] = ""
        cfg["registry"]["username"] = ""
        errors = _validate(cfg)
        assert len(errors) >= 3
