"""Generates AAP 2.6 containerized installer inventory files from wizard config."""

from __future__ import annotations

from app.models import (
    DeploymentConfig,
    Topology,
    InstallationType,
    DatabaseType,
)


class InventoryGenerator:
    def __init__(self, config: DeploymentConfig):
        self.c = config

    @staticmethod
    def _quote_ini(value: str) -> str:
        """Quote a value for INI inventory if it contains special characters."""
        if not value:
            return value
        # If value contains spaces, #, =, or quotes, wrap in single quotes
        if any(c in value for c in (' ', '#', '=', "'", '"', '\n', ';')):
            # Escape single quotes inside by doubling them
            return "'" + value.replace("'", "'\"'\"'") + "'"
        return value

    def validate(self) -> list[str]:
        errors: list[str] = []
        if not self.c.gateway.admin_password:
            errors.append("Gateway admin password is required.")
        if not self.c.database.admin_password:
            errors.append("Database admin password is required.")
        if (
            self.c.installation_type == InstallationType.ONLINE
            and not self.c.registry.username
        ):
            errors.append("Registry username is required for online installations.")
        if (
            self.c.installation_type == InstallationType.ONLINE
            and not self.c.registry.password
        ):
            errors.append("Registry password is required for online installations.")
        if not self.c.gateway.hosts:
            errors.append("At least one gateway host is required.")
        if not self.c.controller.hosts:
            errors.append("At least one controller host is required.")
        if self.c.topology == Topology.ENTERPRISE:
            if len(self.c.gateway.hosts) < 2:
                errors.append("Enterprise topology requires at least 2 gateway hosts.")
            if len(self.c.controller.hosts) < 2:
                errors.append(
                    "Enterprise topology requires at least 2 controller hosts."
                )
        return errors

    def render(self) -> str:
        lines: list[str] = []
        is_growth = self.c.topology == Topology.GROWTH
        is_online = self.c.installation_type == InstallationType.ONLINE

        lines.append(
            "# AAP 2.6 Containerized Installation Inventory"
        )
        lines.append(
            f"# Topology: {'Growth (All-in-one)' if is_growth else 'Enterprise'}"
        )
        lines.append(
            f"# Installation type: {'Online' if is_online else 'Disconnected (Bundled)'}"
        )
        lines.append(
            "# Generated by AAP Deployment Wizard"
        )
        lines.append("")

        # Gateway
        lines.append("[automationgateway]")
        for h in self.c.gateway.hosts:
            lines.append(h)
        lines.append("")

        # Controller
        lines.append("[automationcontroller]")
        for h in self.c.controller.hosts:
            lines.append(h)
        lines.append("")

        # Execution nodes (enterprise only)
        if not is_growth and self.c.execution_nodes:
            lines.append("[execution_nodes]")
            for node in self.c.execution_nodes:
                extra = (
                    f" receptor_type='{node.receptor_type}'"
                    if node.receptor_type != "execution"
                    else ""
                )
                lines.append(f"{node.host}{extra}")
            lines.append("")

        # Hub
        lines.append("[automationhub]")
        for h in self.c.hub.hosts:
            lines.append(h)
        lines.append("")

        # EDA
        lines.append("[automationeda]")
        for h in self.c.eda.hosts:
            lines.append(h)
        lines.append("")

        # Database (growth only — managed)
        if is_growth and self.c.database.type == DatabaseType.MANAGED:
            lines.append("[database]")
            lines.append(self.c.gateway.hosts[0])
            lines.append("")

        # Redis (enterprise)
        if not is_growth:
            lines.append("[redis]")
            for h in self.c.gateway.hosts:
                lines.append(h)
            for h in self.c.hub.hosts:
                lines.append(h)
            for h in self.c.eda.hosts:
                lines.append(h)
            lines.append("")

        # ---------- [all:vars] ----------
        lines.append("[all:vars]")
        lines.append("")

        # Growth topology uses local connection ONLY when not deploying remotely.
        # When target_host is set, the deployer SSHes in and runs ansible-playbook
        # on the target itself, so ansible_connection=local is correct (no nested SSH).
        if is_growth:
            lines.append("ansible_connection=local")
            lines.append("")

        # SSH & become passwords — needed even for local connection when tasks
        # use become (sudo). Only set when target credentials are provided.
        if self.c.target_host and self.c.target_password:
            lines.append("ansible_become_password=" + self._quote_ini(self.c.target_password))
            lines.append("")

        # Common
        lines.append("postgresql_admin_username=" + self.c.database.admin_username)
        lines.append("postgresql_admin_password=" + self._quote_ini(self.c.database.admin_password))
        lines.append("")

        if is_online:
            lines.append("registry_username=" + self.c.registry.username)
            lines.append("registry_password=" + self._quote_ini(self.c.registry.password))
        else:
            lines.append("bundle_install=true")
            if self.c.bundle_dir:
                lines.append("bundle_dir=" + self.c.bundle_dir)
        lines.append("")

        lines.append("redis_mode=" + self.c.redis_mode.value)
        lines.append("")

        # Network
        if self.c.network.tls.disable_https:
            lines.append("envoy_disable_https=true")
        if self.c.network.https_port != 443:
            lines.append(f"envoy_https_port={self.c.network.https_port}")
        if self.c.network.http_port != 80:
            lines.append(f"envoy_http_port={self.c.network.http_port}")
        if self.c.network.tls.custom_ca_cert:
            lines.append("custom_ca_cert=" + self.c.network.tls.custom_ca_cert)
        if self.c.network.tls.custom_server_cert:
            lines.append("custom_server_cert=" + self.c.network.tls.custom_server_cert)
        if self.c.network.tls.custom_server_key:
            lines.append("custom_server_key=" + self.c.network.tls.custom_server_key)
        lines.append("")

        # Gateway
        lines.append("gateway_admin_password=" + self._quote_ini(self.c.gateway.admin_password))
        pg_host = (
            self.c.gateway.pg_host
            or (self.c.gateway.hosts[0] if is_growth else "externaldb.example.org")
        )
        lines.append("gateway_pg_host=" + pg_host)
        if not is_growth:
            lines.append("gateway_pg_database=" + self.c.gateway.pg_database)
            lines.append("gateway_pg_username=" + self.c.gateway.pg_username)
        lines.append("gateway_pg_password=" + self._quote_ini(self.c.gateway.pg_password))
        lines.append("")

        # Controller
        lines.append("controller_admin_password=" + self._quote_ini(self.c.controller.admin_password))
        pg_host = (
            self.c.controller.pg_host
            or (
                self.c.controller.hosts[0] if is_growth else "externaldb.example.org"
            )
        )
        lines.append("controller_pg_host=" + pg_host)
        if not is_growth:
            lines.append("controller_pg_database=" + self.c.controller.pg_database)
            lines.append("controller_pg_username=" + self.c.controller.pg_username)
        lines.append("controller_pg_password=" + self._quote_ini(self.c.controller.pg_password))
        if self.c.controller.percent_memory_capacity != 0.5:
            lines.append(
                f"controller_percent_memory_capacity={self.c.controller.percent_memory_capacity}"
            )
        lines.append("")

        # Hub
        lines.append("hub_admin_password=" + self._quote_ini(self.c.hub.admin_password))
        pg_host = (
            self.c.hub.pg_host
            or (self.c.hub.hosts[0] if is_growth else "externaldb.example.org")
        )
        lines.append("hub_pg_host=" + pg_host)
        if not is_growth:
            lines.append("hub_pg_database=" + self.c.hub.pg_database)
            lines.append("hub_pg_username=" + self.c.hub.pg_username)
        lines.append("hub_pg_password=" + self._quote_ini(self.c.hub.pg_password))
        lines.append(f"hub_seed_collections={'true' if self.c.hub.seed_collections else 'false'}")
        lines.append("")

        # EDA
        lines.append("eda_admin_password=" + self._quote_ini(self.c.eda.admin_password))
        pg_host = (
            self.c.eda.pg_host
            or (self.c.eda.hosts[0] if is_growth else "externaldb.example.org")
        )
        lines.append("eda_pg_host=" + pg_host)
        if not is_growth:
            lines.append("eda_pg_database=" + self.c.eda.pg_database)
            lines.append("eda_pg_username=" + self.c.eda.pg_username)
        lines.append("eda_pg_password=" + self._quote_ini(self.c.eda.pg_password))
        if self.c.eda.safe_plugins:
            lines.append("eda_safe_plugins=" + str(self.c.eda.safe_plugins))
        lines.append("")

        # ---------- Advanced Variables ----------
        adv = self.c.advanced
        adv_lines: list[str] = []

        # Common / Registry
        c = adv.common
        if c.registry_url != "registry.redhat.io":
            adv_lines.append(f"registry_url={c.registry_url}")
        if not c.registry_auth:
            adv_lines.append("registry_auth=false")
        if not c.registry_tls_verify:
            adv_lines.append("registry_tls_verify=false")
        if c.registry_ns_aap != "ansible-automation-platform-26":
            adv_lines.append(f"registry_ns_aap={c.registry_ns_aap}")
        if c.registry_ns_rhel != "rhel9":
            adv_lines.append(f"registry_ns_rhel={c.registry_ns_rhel}")
        if c.ca_tls_cert:
            adv_lines.append(f"ca_tls_cert={c.ca_tls_cert}")
        if c.ca_tls_key:
            adv_lines.append(f"ca_tls_key={c.ca_tls_key}")
        if c.ca_tls_key_passphrase:
            adv_lines.append(f"ca_tls_key_passphrase={c.ca_tls_key_passphrase}")
        if c.ca_tls_remote:
            adv_lines.append("ca_tls_remote=true")
        if c.client_request_timeout != 30:
            adv_lines.append(f"client_request_timeout={c.client_request_timeout}")
        if c.container_compress != "gzip":
            adv_lines.append(f"container_compress={c.container_compress}")
        if c.container_keep_images:
            adv_lines.append("container_keep_images=true")
        if not c.container_pull_images:
            adv_lines.append("container_pull_images=false")
        if c.feature_flags:
            adv_lines.append(f"feature_flags={c.feature_flags}")
        if c.images_tmp_dir:
            adv_lines.append(f"images_tmp_dir={c.images_tmp_dir}")

        # Host tuning
        ht = adv.host_tuning
        if not ht.tune_host_limits:
            adv_lines.append("tune_host_limits=false")
        if ht.host_tuning_sysctl_fs_inotify_max_user_instances != 8192:
            adv_lines.append(f"host_tuning_sysctl_fs_inotify_max_user_instances={ht.host_tuning_sysctl_fs_inotify_max_user_instances}")
        if ht.host_tuning_sysctl_fs_inotify_max_user_watches != 524288:
            adv_lines.append(f"host_tuning_sysctl_fs_inotify_max_user_watches={ht.host_tuning_sysctl_fs_inotify_max_user_watches}")
        if ht.host_tuning_nofile_limit_soft != 524288:
            adv_lines.append(f"host_tuning_nofile_limit_soft={ht.host_tuning_nofile_limit_soft}")
        if ht.host_tuning_nofile_limit_hard != 524288:
            adv_lines.append(f"host_tuning_nofile_limit_hard={ht.host_tuning_nofile_limit_hard}")

        # Advanced Controller
        ac = adv.controller
        self._emit_str(adv_lines, "controller_admin_user", ac.admin_user, "admin")
        if not ac.create_preload_data:
            adv_lines.append("controller_create_preload_data=false")
        if ac.event_workers != 4:
            adv_lines.append(f"controller_event_workers={ac.event_workers}")
        self._emit_str(adv_lines, "controller_license_file", ac.license_file)
        self._emit_str(adv_lines, "controller_nginx_client_max_body_size", ac.nginx_client_max_body_size, "5m")
        self._emit_bool(adv_lines, "controller_nginx_disable_hsts", ac.nginx_disable_hsts)
        self._emit_bool(adv_lines, "controller_nginx_disable_https", ac.nginx_disable_https)
        if ac.nginx_hsts_max_age != 63072000:
            adv_lines.append(f"controller_nginx_hsts_max_age={ac.nginx_hsts_max_age}")
        if ac.nginx_http_port != 8080:
            adv_lines.append(f"controller_nginx_http_port={ac.nginx_http_port}")
        if ac.nginx_https_port != 8443:
            adv_lines.append(f"controller_nginx_https_port={ac.nginx_https_port}")
        self._emit_bool(adv_lines, "controller_pg_cert_auth", ac.pg_cert_auth)
        if ac.pg_port != 5432:
            adv_lines.append(f"controller_pg_port={ac.pg_port}")
        self._emit_str(adv_lines, "controller_pg_sslmode", ac.pg_sslmode, "prefer")
        self._emit_str(adv_lines, "controller_pg_tls_cert", ac.pg_tls_cert)
        self._emit_str(adv_lines, "controller_pg_tls_key", ac.pg_tls_key)
        self._emit_str(adv_lines, "controller_secret_key", ac.secret_key)
        self._emit_str(adv_lines, "controller_tls_cert", ac.tls_cert)
        self._emit_str(adv_lines, "controller_tls_key", ac.tls_key)
        self._emit_bool(adv_lines, "controller_tls_remote", ac.tls_remote)
        if ac.uwsgi_listen_queue_size != 2048:
            adv_lines.append(f"controller_uwsgi_listen_queue_size={ac.uwsgi_listen_queue_size}")
        self._emit_str(adv_lines, "controller_uwsgi_processes", ac.uwsgi_processes)
        self._emit_bool(adv_lines, "controller_postinstall", ac.postinstall)
        self._emit_str(adv_lines, "controller_postinstall_dir", ac.postinstall_dir)
        self._emit_str(adv_lines, "controller_postinstall_repo_url", ac.postinstall_repo_url)
        self._emit_str(adv_lines, "controller_postinstall_repo_ref", ac.postinstall_repo_ref, "main")

        # Advanced Gateway
        ag = adv.gateway
        self._emit_str(adv_lines, "gateway_admin_user", ag.admin_user, "admin")
        self._emit_str(adv_lines, "gateway_main_url", ag.main_url)
        self._emit_str(adv_lines, "gateway_nginx_client_max_body_size", ag.nginx_client_max_body_size, "5m")
        self._emit_bool(adv_lines, "gateway_nginx_disable_hsts", ag.nginx_disable_hsts)
        self._emit_bool(adv_lines, "gateway_nginx_disable_https", ag.nginx_disable_https)
        if ag.nginx_hsts_max_age != 63072000:
            adv_lines.append(f"gateway_nginx_hsts_max_age={ag.nginx_hsts_max_age}")
        if ag.nginx_http_port != 8083:
            adv_lines.append(f"gateway_nginx_http_port={ag.nginx_http_port}")
        if ag.nginx_https_port != 8446:
            adv_lines.append(f"gateway_nginx_https_port={ag.nginx_https_port}")
        self._emit_bool(adv_lines, "gateway_pg_cert_auth", ag.pg_cert_auth)
        if ag.pg_port != 5432:
            adv_lines.append(f"gateway_pg_port={ag.pg_port}")
        self._emit_str(adv_lines, "gateway_pg_sslmode", ag.pg_sslmode, "prefer")
        self._emit_str(adv_lines, "gateway_pg_tls_cert", ag.pg_tls_cert)
        self._emit_str(adv_lines, "gateway_pg_tls_key", ag.pg_tls_key)
        self._emit_bool(adv_lines, "gateway_redis_disable_tls", ag.redis_disable_tls)
        self._emit_str(adv_lines, "gateway_redis_host", ag.redis_host)
        self._emit_str(adv_lines, "gateway_redis_password", ag.redis_password)
        if ag.redis_port != 6379:
            adv_lines.append(f"gateway_redis_port={ag.redis_port}")
        self._emit_str(adv_lines, "gateway_redis_username", ag.redis_username, "gateway")
        self._emit_str(adv_lines, "gateway_secret_key", ag.secret_key)
        self._emit_str(adv_lines, "gateway_tls_cert", ag.tls_cert)
        self._emit_str(adv_lines, "gateway_tls_key", ag.tls_key)
        self._emit_bool(adv_lines, "gateway_tls_remote", ag.tls_remote)
        if ag.uwsgi_listen_queue_size != 4096:
            adv_lines.append(f"gateway_uwsgi_listen_queue_size={ag.uwsgi_listen_queue_size}")
        self._emit_str(adv_lines, "gateway_uwsgi_processes", ag.uwsgi_processes)
        if ag.grpc_server_processes != 5:
            adv_lines.append(f"gateway_grpc_server_processes={ag.grpc_server_processes}")
        if ag.grpc_server_max_threads_per_process != 10:
            adv_lines.append(f"gateway_grpc_server_max_threads_per_process={ag.grpc_server_max_threads_per_process}")

        # Advanced Hub
        ah = adv.hub
        self._emit_str(adv_lines, "hub_storage_backend", ah.storage_backend, "file")
        self._emit_str(adv_lines, "hub_shared_data_path", ah.shared_data_path)
        self._emit_str(adv_lines, "hub_shared_data_mount_opts", ah.shared_data_mount_opts, "rw,sync,hard")
        self._emit_str(adv_lines, "hub_nginx_client_max_body_size", ah.nginx_client_max_body_size, "20m")
        self._emit_bool(adv_lines, "hub_nginx_disable_hsts", ah.nginx_disable_hsts)
        self._emit_bool(adv_lines, "hub_nginx_disable_https", ah.nginx_disable_https)
        self._emit_bool(adv_lines, "hub_pg_cert_auth", ah.pg_cert_auth)
        if ah.pg_port != 5432:
            adv_lines.append(f"hub_pg_port={ah.pg_port}")
        self._emit_str(adv_lines, "hub_pg_sslmode", ah.pg_sslmode, "prefer")
        self._emit_str(adv_lines, "hub_secret_key", ah.secret_key)
        self._emit_str(adv_lines, "hub_tls_cert", ah.tls_cert)
        self._emit_str(adv_lines, "hub_tls_key", ah.tls_key)
        if ah.workers != 2:
            adv_lines.append(f"hub_workers={ah.workers}")
        self._emit_str(adv_lines, "hub_api_workers", ah.api_workers)
        self._emit_bool(adv_lines, "hub_collection_signing", ah.collection_signing)
        self._emit_str(adv_lines, "hub_collection_signing_key", ah.collection_signing_key)
        self._emit_bool(adv_lines, "hub_container_signing", ah.container_signing)
        self._emit_str(adv_lines, "hub_container_signing_key", ah.container_signing_key)
        self._emit_bool(adv_lines, "hub_postinstall", ah.postinstall)
        self._emit_str(adv_lines, "hub_postinstall_dir", ah.postinstall_dir)
        self._emit_str(adv_lines, "hub_postinstall_repo_url", ah.postinstall_repo_url)

        # Advanced EDA
        ae = adv.eda
        if ae.activation_workers != 2:
            adv_lines.append(f"eda_activation_workers={ae.activation_workers}")
        if ae.workers != 2:
            adv_lines.append(f"eda_workers={ae.workers}")
        self._emit_str(adv_lines, "eda_gunicorn_workers", ae.gunicorn_workers)
        self._emit_bool(adv_lines, "eda_debug", ae.debug)
        self._emit_str(adv_lines, "eda_type", ae.type, "hybrid")
        self._emit_str(adv_lines, "eda_nginx_client_max_body_size", ae.nginx_client_max_body_size, "1m")
        self._emit_bool(adv_lines, "eda_nginx_disable_hsts", ae.nginx_disable_hsts)
        self._emit_bool(adv_lines, "eda_nginx_disable_https", ae.nginx_disable_https)
        self._emit_bool(adv_lines, "eda_pg_cert_auth", ae.pg_cert_auth)
        if ae.pg_port != 5432:
            adv_lines.append(f"eda_pg_port={ae.pg_port}")
        self._emit_str(adv_lines, "eda_pg_sslmode", ae.pg_sslmode, "prefer")
        self._emit_bool(adv_lines, "eda_redis_disable_tls", ae.redis_disable_tls)
        self._emit_str(adv_lines, "eda_redis_host", ae.redis_host)
        self._emit_str(adv_lines, "eda_redis_password", ae.redis_password)
        if ae.redis_port != 6379:
            adv_lines.append(f"eda_redis_port={ae.redis_port}")
        self._emit_str(adv_lines, "eda_redis_username", ae.redis_username, "eda")
        self._emit_str(adv_lines, "eda_secret_key", ae.secret_key)
        self._emit_str(adv_lines, "eda_tls_cert", ae.tls_cert)
        self._emit_str(adv_lines, "eda_tls_key", ae.tls_key)

        # Advanced Database
        db = adv.database
        self._emit_str(adv_lines, "postgresql_admin_database", db.postgresql_admin_database, "postgres")
        self._emit_bool(adv_lines, "postgresql_disable_tls", db.postgresql_disable_tls)
        self._emit_str(adv_lines, "postgresql_effective_cache_size", db.postgresql_effective_cache_size)
        self._emit_bool(adv_lines, "postgresql_keep_databases", db.postgresql_keep_databases)
        if db.postgresql_max_connections != 1024:
            adv_lines.append(f"postgresql_max_connections={db.postgresql_max_connections}")
        self._emit_str(adv_lines, "postgresql_password_encryption", db.postgresql_password_encryption, "scram-sha-256")
        self._emit_str(adv_lines, "postgresql_shared_buffers", db.postgresql_shared_buffers)
        if db.postgresql_port != 5432:
            adv_lines.append(f"postgresql_port={db.postgresql_port}")
        self._emit_str(adv_lines, "postgresql_tls_cert", db.postgresql_tls_cert)
        self._emit_str(adv_lines, "postgresql_tls_key", db.postgresql_tls_key)

        # Advanced Receptor
        rc = adv.receptor
        self._emit_bool(adv_lines, "receptor_disable_signing", rc.disable_signing)
        self._emit_bool(adv_lines, "receptor_disable_tls", rc.disable_tls)
        self._emit_str(adv_lines, "receptor_log_level", rc.log_level, "info")
        self._emit_bool(adv_lines, "receptor_mintls13", rc.mintls13)
        if rc.port != 27199:
            adv_lines.append(f"receptor_port={rc.port}")
        self._emit_str(adv_lines, "receptor_protocol", rc.protocol, "tcp")
        self._emit_str(adv_lines, "receptor_signing_private_key", rc.signing_private_key)
        self._emit_str(adv_lines, "receptor_signing_public_key", rc.signing_public_key)
        self._emit_str(adv_lines, "receptor_tls_cert", rc.tls_cert)
        self._emit_str(adv_lines, "receptor_tls_key", rc.tls_key)

        # Advanced Redis
        rd = adv.redis
        self._emit_str(adv_lines, "redis_cluster_ip", rd.cluster_ip)
        self._emit_bool(adv_lines, "redis_disable_tls", rd.disable_tls)
        if rd.port != 6379:
            adv_lines.append(f"redis_port={rd.port}")
        self._emit_bool(adv_lines, "redis_prefer_ipv6", rd.prefer_ipv6)
        self._emit_str(adv_lines, "redis_tls_cert", rd.tls_cert)
        self._emit_str(adv_lines, "redis_tls_key", rd.tls_key)

        # Lightspeed
        ls = adv.lightspeed
        if ls.enabled and ls.admin_password:
            adv_lines.append(f"lightspeed_admin_password={ls.admin_password}")
            self._emit_str(adv_lines, "lightspeed_admin_user", ls.admin_user, "admin")
            self._emit_str(adv_lines, "lightspeed_pg_host", ls.pg_host)
            self._emit_str(adv_lines, "lightspeed_pg_password", ls.pg_password)
            self._emit_str(adv_lines, "lightspeed_pg_database", ls.pg_database, "lightspeed")
            self._emit_str(adv_lines, "lightspeed_pg_username", ls.pg_username, "lightspeed")
            self._emit_str(adv_lines, "lightspeed_chatbot_model_url", ls.chatbot_model_url)
            self._emit_str(adv_lines, "lightspeed_chatbot_model_api_key", ls.chatbot_model_api_key)
            self._emit_str(adv_lines, "lightspeed_chatbot_model_id", ls.chatbot_model_id)
            self._emit_str(adv_lines, "lightspeed_chatbot_default_provider", ls.chatbot_default_provider, "rhoai")
            self._emit_str(adv_lines, "lightspeed_wca_model_api_key", ls.wca_model_api_key)
            self._emit_str(adv_lines, "lightspeed_wca_model_id", ls.wca_model_id)
            self._emit_bool(adv_lines, "lightspeed_mcp_controller_enabled", ls.mcp_controller_enabled)
            self._emit_bool(adv_lines, "lightspeed_mcp_lightspeed_enabled", ls.mcp_lightspeed_enabled)

        # Monitoring
        mo = adv.monitoring
        self._emit_bool(adv_lines, "setup_monitoring", mo.setup_monitoring)
        if mo.pcp_pmcd_port != 44321:
            adv_lines.append(f"pcp_pmcd_port={mo.pcp_pmcd_port}")
        if mo.pcp_pmproxy_port != 44322:
            adv_lines.append(f"pcp_pmproxy_port={mo.pcp_pmproxy_port}")
        self._emit_str(adv_lines, "pcp_firewall_zone", mo.pcp_firewall_zone, "public")
        self._emit_bool(adv_lines, "metrics_utility_enabled", mo.metrics_utility_enabled)

        if adv_lines:
            lines.append("# Advanced Variables")
            lines.extend(adv_lines)
            lines.append("")

        # Lightspeed host group (if enabled)
        if ls.enabled:
            host = ls.pg_host or (self.c.gateway.hosts[0] if self.c.gateway.hosts else "aap.example.org")
            output = "\n".join(lines)
            lightspeed_block = f"\n[ansiblelightspeed]\n{host}\n"
            insert_pos = output.find("[all:vars]")
            if insert_pos > 0:
                return output[:insert_pos] + lightspeed_block + "\n" + output[insert_pos:]

        return "\n".join(lines)

    @staticmethod
    def _emit_str(lines: list[str], var: str, value: str, default: str = "") -> None:
        if value and value != default:
            lines.append(f"{var}={value}")

    @staticmethod
    def _emit_bool(lines: list[str], var: str, value: bool, when_true: bool = True) -> None:
        if value == when_true and value:
            lines.append(f"{var}=true")
        elif not value and not when_true:
            lines.append(f"{var}=false")
